version: '3.8'

services:
  rabbitmq:
    container_name: 'guide-rabbit'
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'

    depends_on:
      - db
      - rabbitmq




volumes:
  mysql_data:

